import type { ComponentProps } from 'react'
import {
  ArrowLeft,
  Basket,
  Bell,
  Camera,
  CheckCircle,
  Bus,
  Car,
  ChartBar,
  ChartLineUp,
  ChartPieSlice,
  Coffee,
  CreditCard,
  DotsThree,
  DotsThreeCircle,
  Envelope,
  Eye,
  EyeSlash,
  FileText,
  FilmSlate,
  ForkKnife,
  GameController,
  Gear,
  Gift,
  House,
  ImageSquare,
  Lightbulb,
  ListDashes,
  Lock,
  Moon,
  Plus,
  Receipt,
  Robot,
  ShoppingCart,
  SoccerBall,
  Sun,
  TrendUp,
  Trash,
  TrayArrowDown,
  UploadSimple,
  X,
  UsersThree,
  Wallet,
} from 'phosphor-react-native'

const iconMap = {
  home: House,
  transactions: ListDashes,
  capture: Plus,
  reports: ChartLineUp,
  settings: Gear,
  wallets: Wallet,
  budgets: ChartPieSlice,
  bills: Receipt,
  groups: UsersThree,
  imports: TrayArrowDown,
  upload: UploadSimple,
  lock: Lock,
  email: Envelope,
  eye: Eye,
  eyeSlash: EyeSlash,
  moon: Moon,
  sun: Sun,
  back: ArrowLeft,
  insight: Lightbulb,
  ai: Robot,
  chart: ChartBar,
  file: FileText,
  card: CreditCard,
  notification: Bell,
  camera: Camera,
  image: ImageSquare,
  trash: Trash,
  check: CheckCircle,
  close: X,
  food: ForkKnife,
  coffee: Coffee,
  transport: Car,
  bus: Bus,
  sport: SoccerBall,
  recreation: GameController,
  movie: FilmSlate,
  groceries: ShoppingCart,
  basket: Basket,
  investment: TrendUp,
  gift: Gift,
  more: DotsThree,
  otherExpenses: DotsThreeCircle,
} as const

export type KaswiseIconName = keyof typeof iconMap
export const kaswiseIconNames = Object.keys(iconMap) as KaswiseIconName[]

type IconProps = Omit<ComponentProps<typeof House>, 'weight'> & {
  name: KaswiseIconName
  weight?: ComponentProps<typeof House>['weight']
}

export function KaswiseIcon({ name, weight = 'regular', ...props }: IconProps) {
  const Icon = iconMap[name] ?? House
  return <Icon weight={weight} {...props} />
}
