import { StyleSheet } from 'react-native'
import type { MobileTheme } from '../theme/mobile-theme'

export function createMobileStyles(theme: MobileTheme) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: theme.colors.background },
    container: { flex: 1, backgroundColor: theme.colors.background, padding: 16 },
    sectionCard: {
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      borderRadius: 16,
      padding: 14,
      gap: 10,
    },
    sectionTitle: { color: theme.colors.textPrimary, fontSize: 16, fontWeight: '700' },
    sectionSub: { color: theme.colors.textSecondary, fontSize: 12 },
    borderTop: { borderTopWidth: 1, borderTopColor: theme.colors.borderSoft },
  })
}

export const colors = {
  background: '#F0F4FF',
  card: '#FFFFFF',
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  primarySoft: '#EAF2FF',
  border: '#D7E2F7',
  text: '#0F172A',
  muted: '#64748B',
  mutedSoft: '#94A3B8',
  success: '#10B981',
  warning: '#F59E0B',
  danger: '#EF4444',
  iconBg: '#EEF3FF',
} as const

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flexGrow: 1,
    padding: 16,
    justifyContent: 'center',
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  appContent: {
    padding: 14,
    paddingBottom: 120,
  },
  screenWrap: {
    gap: 14,
  },
  mobileTopbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mobileTopbarTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  mobileTopbarSub: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 2,
  },
  avatarBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarBadgeText: {
    color: colors.card,
    fontSize: 11,
    fontWeight: '700',
  },
  mobileHero: {
    backgroundColor: colors.primary,
    borderRadius: 20,
    padding: 18,
    gap: 10,
  },
  mobileHeroLabel: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 12,
    fontWeight: '600',
  },
  mobileHeroAmount: {
    color: colors.card,
    fontSize: 30,
    fontWeight: '800',
  },
  mobileHeroStats: {
    flexDirection: 'row',
    gap: 8,
  },
  heroMiniStat: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 14,
    padding: 10,
    gap: 2,
  },
  heroMiniStatLabel: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 10,
  },
  heroMiniStatValue: {
    color: colors.card,
    fontSize: 13,
    fontWeight: '700',
  },
  quickActionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quickActionCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 6,
  },
  quickActionIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.iconBg,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 28,
    overflow: 'hidden',
  },
  quickActionLabel: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '600',
  },
  sectionCard: {
    backgroundColor: colors.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    gap: 10,
  },
  sectionCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionCardTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  sectionCardAction: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  inlineBudgetCard: {
    gap: 6,
  },
  inlineBudgetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inlineBudgetTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  inlineBudgetPct: {
    color: colors.warning,
    fontSize: 12,
    fontWeight: '700',
  },
  inlineBudgetMeta: {
    color: colors.muted,
    fontSize: 12,
  },
  progressTrack: {
    height: 7,
    backgroundColor: '#E2E8F0',
    borderRadius: 999,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  transactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 6,
  },
  transactionIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transactionIconText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  transactionContent: {
    flex: 1,
  },
  transactionMerchant: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  transactionSub: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 2,
  },
  transactionAmount: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '700',
  },
  transactionAmountPositive: {
    color: colors.success,
  },
  floatingActionWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 62,
    alignItems: 'center',
    pointerEvents: 'box-none',
  },
  floatingActionButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 10,
  },
  floatingActionText: {
    color: colors.card,
    fontSize: 28,
    fontWeight: '700',
    marginTop: -2,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 8,
    paddingBottom: 10,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  bottomNavIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavIconActive: {
    backgroundColor: colors.primary,
  },
  bottomNavIconText: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
  },
  bottomNavIconTextActive: {
    color: colors.card,
  },
  bottomNavLabel: {
    color: colors.mutedSoft,
    fontSize: 11,
    fontWeight: '600',
  },
  bottomNavLabelActive: {
    color: colors.primary,
  },
  screenHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  screenHeaderTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  screenHeaderSubtitle: {
    color: colors.muted,
    fontSize: 13,
    marginTop: 2,
  },
  headerAction: {
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  headerActionText: {
    color: colors.card,
    fontSize: 12,
    fontWeight: '700',
  },
  pillRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  monthChipRow: {
    flexDirection: 'row',
    gap: 8,
  },
  monthChip: {
    flex: 1,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  monthChipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  monthChipText: {
    color: colors.mutedSoft,
    fontSize: 12,
    fontWeight: '700',
  },
  monthChipTextActive: {
    color: colors.primary,
  },
  budgetCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  budgetCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  budgetCardTitleWrap: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  budgetCardEmoji: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.iconBg,
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 28,
    overflow: 'hidden',
  },
  budgetCardTitle: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  budgetCardMeta: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 2,
  },
  budgetCardPct: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  budgetCardFooter: {
    color: colors.muted,
    fontSize: 12,
  },
  reportMetricRow: {
    flexDirection: 'row',
    gap: 10,
  },
  metricCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 14,
    gap: 4,
  },
  metricCardLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  metricCardValue: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  chartMock: {
    height: 160,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 16,
  },
  chartBar: {
    flex: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  chartCaption: {
    color: colors.muted,
    fontSize: 12,
    marginTop: 8,
  },
  categoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  categoryLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  categoryValue: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  moreRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    paddingVertical: 6,
  },
  moreIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: colors.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreIcon: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  moreContent: {
    flex: 1,
  },
  moreLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  moreHelper: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 2,
  },
  splashScreen: {
    flex: 1,
    padding: 24,
    backgroundColor: colors.primaryDark,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  splashOrbTop: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  splashOrbBottom: {
    position: 'absolute',
    bottom: -30,
    left: -30,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  splashLogo: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  splashLogoText: {
    color: colors.card,
    fontSize: 20,
    fontWeight: '800',
  },
  splashTitle: {
    color: colors.card,
    fontSize: 34,
    fontWeight: '800',
    marginBottom: 8,
  },
  splashSubtitle: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 26,
  },
  splashActions: {
    width: '100%',
    gap: 10,
  },
  whiteButton: {
    backgroundColor: colors.card,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  whiteButtonText: {
    color: colors.primaryDark,
    fontSize: 15,
    fontWeight: '700',
  },
  ghostButton: {
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  ghostButtonText: {
    color: colors.card,
    fontSize: 14,
    fontWeight: '600',
  },
  stepCard: {
    backgroundColor: colors.background,
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  skipText: {
    alignSelf: 'flex-end',
    color: colors.mutedSoft,
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 12,
  },
  progressRow: {
    flexDirection: 'row',
    gap: 4,
    marginBottom: 16,
  },
  progressSegment: {
    flex: 1,
    height: 4,
    borderRadius: 999,
  },
  progressDone: {
    backgroundColor: colors.primary,
  },
  progressActive: {
    backgroundColor: '#3B82F6',
  },
  progressIdle: {
    backgroundColor: colors.border,
  },
  featureHero: {
    height: 140,
    borderRadius: 18,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    overflow: 'hidden',
  },
  featureBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  featureBadgeText: {
    color: colors.card,
    fontSize: 11,
    fontWeight: '700',
  },
  featureHeroEmoji: {
    color: colors.primary,
    fontSize: 40,
    fontWeight: '800',
  },
  stepTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
    marginBottom: 10,
  },
  stepDescription: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 24,
  },
  setupTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 4,
  },
  setupSubtitle: {
    color: colors.mutedSoft,
    fontSize: 13,
    marginBottom: 16,
  },
  fieldGroup: {
    marginBottom: 16,
  },
  fieldLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  fieldBox: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  fieldBoxActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  fieldValue: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
  walletGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  walletChip: {
    width: '47%',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  walletChipActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  walletChipIdle: {
    backgroundColor: colors.card,
    borderColor: colors.border,
  },
  walletChipEmoji: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.iconBg,
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 24,
    overflow: 'hidden',
  },
  walletChipText: {
    fontSize: 14,
    fontWeight: '600',
  },
  walletChipTextActive: {
    color: colors.primary,
  },
  walletChipTextIdle: {
    color: '#475569',
  },
  navigationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 8,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: colors.muted,
    fontSize: 18,
    fontWeight: '700',
  },
  nextButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
  },
  nextButtonText: {
    color: colors.card,
    fontSize: 14,
    fontWeight: '700',
  },
  welcomeWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
  },
  successIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.success,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    shadowColor: colors.success,
    shadowOpacity: 0.28,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 8,
  },
  successIconText: {
    color: colors.card,
    fontSize: 28,
    fontWeight: '800',
  },
  welcomeTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  welcomeDescription: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 20,
    maxWidth: 320,
  },
  welcomeTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
  },
  tag: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  tagText: {
    color: '#475569',
    fontSize: 13,
    fontWeight: '600',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: colors.primary,
    borderRadius: 999,
    paddingVertical: 15,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryButtonText: {
    color: colors.card,
    fontSize: 15,
    fontWeight: '700',
  },
  secondaryLinkButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  secondaryLinkText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  pill: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  pillActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  pillText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  pillTextActive: {
    color: colors.primary,
  },
  iconBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.iconBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBadgeText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
  },
  summaryCard: {
    backgroundColor: colors.card,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    gap: 10,
  },
  summaryCardLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  summaryCardAmount: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '800',
  },
  summaryCardStats: {
    flexDirection: 'row',
    gap: 8,
  },
})
