import { StyleSheet } from 'react-native'
import type { MobileTheme } from '../theme/mobile-theme'

export function createMobileStyles(theme: MobileTheme) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    container: {
      flexGrow: 1,
      padding: theme.spacing.lg,
      justifyContent: 'center',
    },
    appShell: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    appContent: {
      padding: theme.spacing.md,
      paddingBottom: 120,
    },
    screenWrap: {
      gap: theme.spacing.md,
    },
    mobileTopbar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    mobileTopbarTitle: {
      color: theme.colors.textPrimary,
      fontSize: 22,
      fontWeight: '800',
    },
    mobileTopbarSub: {
      color: theme.colors.textSecondary,
      fontSize: 13,
      marginTop: 2,
    },
    avatarBadge: {
      width: 34,
      height: 34,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.brandPrimary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarBadgeText: {
      color: theme.colors.card,
      fontSize: 11,
      fontWeight: '700',
    },
    mobileHero: {
      backgroundColor: theme.colors.brandPrimary,
      borderRadius: theme.radius.xl,
      padding: 18,
      gap: 10,
    },
    mobileHeroLabel: {
      color: `rgba(255,255,255,${theme.opacity[70]})`,
      fontSize: 12,
      fontWeight: '600',
    },
    mobileHeroAmount: {
      color: theme.colors.card,
      fontSize: 30,
      fontWeight: '800',
    },
    mobileHeroStats: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    heroMiniStat: {
      flex: 1,
      backgroundColor: `rgba(255,255,255,${theme.opacity[15]})`,
      borderRadius: theme.radius.md,
      padding: 10,
      gap: 2,
    },
    heroMiniStatLabel: {
      color: `rgba(255,255,255,${theme.opacity[70]})`,
      fontSize: 10,
    },
    heroMiniStatValue: {
      color: theme.colors.card,
      fontSize: 13,
      fontWeight: '700',
    },
    quickActionRow: {
      flexDirection: 'row',
      gap: theme.spacing.sm,
    },
    quickActionCard: {
      flex: 1,
      backgroundColor: theme.colors.card,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.sm,
      alignItems: 'center',
      gap: 6,
    },
    quickActionIcon: {
      width: 28,
      height: 28,
      borderRadius: theme.radius.md,
      backgroundColor: theme.iconBubbles.primary.background,
      borderWidth: 1,
      borderColor: theme.iconBubbles.primary.border,
      color: theme.iconBubbles.primary.color,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
      lineHeight: 28,
      overflow: 'hidden',
    },
    quickActionLabel: {
      color: theme.colors.textSecondary,
      fontSize: 11,
      fontWeight: '600',
    },
    sectionCard: {
      backgroundColor: theme.colors.card,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      padding: theme.spacing.md,
      gap: 10,
    },
    sectionCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    sectionCardTitle: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '700',
    },
    sectionCardAction: {
      color: theme.colors.brandPrimary,
      fontSize: 12,
      fontWeight: '600',
    },
    inlineBudgetCard: { gap: 6 },
    inlineBudgetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    inlineBudgetTitle: { color: theme.colors.textPrimary, fontSize: 13, fontWeight: '700' },
    inlineBudgetPct: { color: theme.colors.warning, fontSize: 12, fontWeight: '700' },
    inlineBudgetMeta: { color: theme.colors.textSecondary, fontSize: 12 },
    progressTrack: {
      height: 7,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.pill,
      overflow: 'hidden',
    },
    progressFill: { height: '100%', borderRadius: theme.radius.pill },
    transactionRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 6 },
    transactionIcon: {
      width: 32,
      height: 32,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.iconBubbles.primary.background,
      borderWidth: 1,
      borderColor: theme.iconBubbles.primary.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    transactionIconText: { color: theme.iconBubbles.primary.color, fontSize: 12, fontWeight: '800' },
    transactionContent: { flex: 1 },
    transactionMerchant: { color: theme.colors.textPrimary, fontSize: 13, fontWeight: '700' },
    transactionSub: { color: theme.colors.textSecondary, fontSize: 11, marginTop: 2 },
    transactionAmount: { color: theme.colors.danger, fontSize: 13, fontWeight: '700' },
    transactionAmountPositive: { color: theme.colors.success },
    floatingActionWrap: {
      position: 'absolute', left: 0, right: 0, bottom: 62, alignItems: 'center', pointerEvents: 'box-none',
    },
    floatingActionButton: {
      width: 58,
      height: 58,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.brandPrimary,
      alignItems: 'center',
      justifyContent: 'center',
      ...theme.shadow.neon,
    },
    floatingActionText: { color: theme.colors.card, fontSize: 28, fontWeight: '700', marginTop: -2 },
    bottomNav: {
      position: 'absolute', left: 0, right: 0, bottom: 0, flexDirection: 'row', backgroundColor: theme.colors.card,
      borderTopWidth: 1, borderTopColor: theme.colors.borderSoft, paddingTop: theme.spacing.sm, paddingBottom: 10,
    },
    bottomNavItem: { flex: 1, alignItems: 'center', gap: 4 },
    bottomNavIcon: {
      width: 28,
      height: 28,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bottomNavIconActive: { backgroundColor: theme.colors.brandPrimary },
    bottomNavIconText: { color: theme.colors.textPrimary, fontSize: 11, fontWeight: '800' },
    bottomNavIconTextActive: { color: theme.colors.card },
    bottomNavLabel: { color: theme.colors.textMuted, fontSize: 11, fontWeight: '600' },
    bottomNavLabelActive: { color: theme.colors.brandPrimary },
    screenHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    screenHeaderTitle: { color: theme.colors.textPrimary, fontSize: 22, fontWeight: '800' },
    screenHeaderSubtitle: { color: theme.colors.textSecondary, fontSize: 13, marginTop: 2 },
    headerAction: {
      backgroundColor: theme.colors.brandPrimary,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      borderRadius: theme.radius.pill,
    },
    headerActionText: { color: theme.colors.card, fontSize: 12, fontWeight: '700' },
    pillRow: { flexDirection: 'row', gap: theme.spacing.sm, flexWrap: 'wrap' },
    monthChipRow: { flexDirection: 'row', gap: theme.spacing.sm },
    monthChip: {
      flex: 1,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      borderRadius: theme.radius.md,
      paddingVertical: 10,
      alignItems: 'center',
    },
    monthChipActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.brandPrimary },
    monthChipText: { color: theme.colors.textMuted, fontSize: 12, fontWeight: '700' },
    monthChipTextActive: { color: theme.colors.brandPrimary },
    budgetCard: { backgroundColor: theme.colors.card, borderWidth: 1, borderColor: theme.colors.borderSoft, borderRadius: theme.radius.lg, padding: theme.spacing.md, gap: theme.spacing.sm },
    budgetCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    budgetCardTitleWrap: { flexDirection: 'row', gap: theme.spacing.sm, alignItems: 'center' },
    budgetCardEmoji: {
      width: 28,
      height: 28,
      borderRadius: theme.radius.md,
      backgroundColor: theme.iconBubbles.primary.background,
      borderWidth: 1,
      borderColor: theme.iconBubbles.primary.border,
      color: theme.iconBubbles.primary.color,
      fontSize: 12,
      fontWeight: '800',
      textAlign: 'center',
      lineHeight: 28,
      overflow: 'hidden',
    },
    budgetCardTitle: { color: theme.colors.textPrimary, fontSize: 14, fontWeight: '700' },
    budgetCardMeta: { color: theme.colors.textSecondary, fontSize: 12, marginTop: 2 },
    budgetCardPct: { color: theme.colors.textPrimary, fontSize: 13, fontWeight: '700' },
    budgetCardFooter: { color: theme.colors.textSecondary, fontSize: 12 },
    reportMetricRow: { flexDirection: 'row', gap: 10 },
    metricCard: { flex: 1, backgroundColor: theme.colors.card, borderWidth: 1, borderColor: theme.colors.borderSoft, borderRadius: theme.radius.lg, padding: theme.spacing.md, gap: 4 },
    metricCardLabel: { color: theme.colors.textSecondary, fontSize: 12, fontWeight: '600' },
    metricCardValue: { color: theme.colors.textPrimary, fontSize: 16, fontWeight: '800' },
    chartMock: { height: 160, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: theme.spacing.sm, paddingTop: theme.spacing.lg },
    chartBar: { flex: 1, borderTopLeftRadius: theme.radius.sm, borderTopRightRadius: theme.radius.sm },
    chartCaption: { color: theme.colors.textSecondary, fontSize: 12, marginTop: theme.spacing.sm },
    categoryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
    categoryLabel: { color: theme.colors.textPrimary, fontSize: 13, fontWeight: '700' },
    categoryValue: { color: theme.colors.brandPrimary, fontSize: 12, fontWeight: '700' },
    moreRow: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 6 },
    moreIconWrap: {
      width: 34,
      height: 34,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.iconBubbles.primary.background,
      borderWidth: 1,
      borderColor: theme.iconBubbles.primary.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    moreIcon: { color: theme.iconBubbles.primary.color, fontSize: 12, fontWeight: '800' },
    moreContent: { flex: 1 },
    moreLabel: { color: theme.colors.textPrimary, fontSize: 13, fontWeight: '700' },
    moreHelper: { color: theme.colors.textSecondary, fontSize: 11, marginTop: 2 },
    splashScreen: { flex: 1, padding: theme.spacing['2xl'], backgroundColor: theme.colors.brandAccent, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
    splashOrbTop: { position: 'absolute', top: -40, right: -40, width: 140, height: 140, borderRadius: 70, backgroundColor: `rgba(255,255,255,${theme.opacity[10]})` },
    splashOrbBottom: { position: 'absolute', bottom: -30, left: -30, width: 120, height: 120, borderRadius: 60, backgroundColor: `rgba(255,255,255,${theme.opacity[10]})` },
    splashLogo: {
      width: 64,
      height: 64,
      borderRadius: theme.radius.lg,
      backgroundColor: theme.colors.glass.background,
      borderWidth: 1,
      borderColor: theme.colors.glass.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
    },
    splashLogoText: { color: theme.colors.card, fontSize: 20, fontWeight: '800' },
    splashTitle: { color: theme.colors.card, fontSize: 34, fontWeight: '800', marginBottom: theme.spacing.sm },
    splashSubtitle: { color: `rgba(255,255,255,${theme.opacity[80]})`, fontSize: 15, lineHeight: 24, textAlign: 'center', marginBottom: 26 },
    splashActions: { width: '100%', gap: 10 },
    whiteButton: { backgroundColor: theme.colors.card, borderRadius: theme.radius.pill, paddingVertical: theme.spacing.md, paddingHorizontal: 18, alignItems: 'center' },
    whiteButtonText: { color: theme.colors.brandAccent, fontSize: 15, fontWeight: '700' },
    ghostButton: {
      backgroundColor: `rgba(255,255,255,${theme.opacity[15]})`,
      borderRadius: theme.radius.pill,
      borderWidth: 1,
      borderColor: theme.colors.glass.border,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: 18,
      alignItems: 'center',
    },
    ghostButtonText: { color: theme.colors.card, fontSize: 14, fontWeight: '600' },
    stepCard: { backgroundColor: theme.colors.background, paddingHorizontal: theme.spacing.sm, paddingVertical: theme.spacing.md },
    skipText: { alignSelf: 'flex-end', color: theme.colors.textMuted, fontSize: 12, fontWeight: '500', marginBottom: theme.spacing.md },
    progressRow: { flexDirection: 'row', gap: 4, marginBottom: theme.spacing.lg },
    progressSegment: { flex: 1, height: 4, borderRadius: theme.radius.pill },
    progressDone: { backgroundColor: theme.colors.brandPrimary },
    progressActive: { backgroundColor: theme.colors.info },
    progressIdle: { backgroundColor: theme.colors.borderSoft },
    featureHero: { height: 140, borderRadius: theme.radius.lg, backgroundColor: theme.colors.surface, alignItems: 'center', justifyContent: 'center', marginBottom: 18, overflow: 'hidden' },
    featureBadge: {
      position: 'absolute',
      top: 10,
      right: 10,
      backgroundColor: theme.colors.brandPrimary,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: theme.radius.pill,
    },
    featureBadgeText: { color: theme.colors.card, fontSize: 11, fontWeight: '700' },
    featureHeroEmoji: { color: theme.colors.brandPrimary, fontSize: 40, fontWeight: '800' },
    stepTitle: { color: theme.colors.textPrimary, fontSize: 28, fontWeight: '800', lineHeight: 34, marginBottom: 10 },
    stepDescription: { color: theme.colors.textSecondary, fontSize: 15, lineHeight: 24, marginBottom: theme.spacing['2xl'] },
    setupTitle: { color: theme.colors.textPrimary, fontSize: 22, fontWeight: '800', marginBottom: 4 },
    setupSubtitle: { color: theme.colors.textMuted, fontSize: 13, marginBottom: theme.spacing.lg },
    fieldGroup: { marginBottom: theme.spacing.lg },
    fieldLabel: { color: theme.colors.textSecondary, fontSize: 13, fontWeight: '600', marginBottom: theme.spacing.sm },
    fieldBox: {
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      borderRadius: theme.radius.md,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
    },
    fieldBoxActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.brandPrimary },
    fieldValue: { color: theme.colors.textPrimary, fontSize: 15, fontWeight: '600' },
    walletGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    walletChip: {
      width: '47%',
      borderRadius: theme.radius.md,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: theme.spacing.md,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    walletChipActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.brandPrimary },
    walletChipIdle: { backgroundColor: theme.colors.card, borderColor: theme.colors.borderSoft },
    walletChipEmoji: {
      width: 24,
      height: 24,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.iconBubbles.primary.background,
      borderWidth: 1,
      borderColor: theme.iconBubbles.primary.border,
      color: theme.iconBubbles.primary.color,
      fontSize: 11,
      fontWeight: '800',
      textAlign: 'center',
      lineHeight: 24,
      overflow: 'hidden',
    },
    walletChipText: { fontSize: 14, fontWeight: '600' },
    walletChipTextActive: { color: theme.colors.brandPrimary },
    walletChipTextIdle: { color: theme.colors.textSecondary },
    navigationRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: theme.spacing.sm },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.card,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backButtonText: { color: theme.colors.textSecondary, fontSize: 18, fontWeight: '700' },
    nextButton: {
      flex: 1,
      backgroundColor: theme.colors.brandPrimary,
      borderRadius: theme.radius.pill,
      paddingVertical: theme.spacing.md,
      paddingHorizontal: 18,
      alignItems: 'center',
      ...theme.shadow.neon,
    },
    nextButtonText: { color: theme.colors.card, fontSize: 14, fontWeight: '700' },
    welcomeWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 28 },
    successIcon: {
      width: 72,
      height: 72,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.success,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
      ...theme.shadow.md,
    },
    successIconText: { color: theme.colors.card, fontSize: 28, fontWeight: '800' },
    welcomeTitle: { color: theme.colors.textPrimary, fontSize: 28, fontWeight: '800', marginBottom: theme.spacing.sm },
    welcomeDescription: { color: theme.colors.textSecondary, fontSize: 15, lineHeight: 24, textAlign: 'center', marginBottom: theme.spacing.xl, maxWidth: 320 },
    welcomeTags: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: theme.spacing.sm, marginBottom: theme.spacing.xl },
    tag: { backgroundColor: theme.colors.card, borderWidth: 1, borderColor: theme.colors.borderSoft, borderRadius: theme.radius.pill, paddingVertical: theme.spacing.sm, paddingHorizontal: theme.spacing.md },
    tagText: { color: theme.colors.textSecondary, fontSize: 13, fontWeight: '600' },
    primaryButton: {
      width: '100%',
      backgroundColor: theme.colors.brandPrimary,
      borderRadius: theme.radius.pill,
      paddingVertical: 15,
      paddingHorizontal: 18,
      alignItems: 'center',
      marginBottom: 10,
      ...theme.shadow.neon,
    },
    primaryButtonText: { color: theme.colors.card, fontSize: 15, fontWeight: '700' },
    secondaryLinkButton: { paddingVertical: theme.spacing.sm, paddingHorizontal: theme.spacing.md },
    secondaryLinkText: { color: theme.colors.textSecondary, fontSize: 13, fontWeight: '600' },
    pill: { backgroundColor: theme.colors.card, borderWidth: 1, borderColor: theme.colors.borderSoft, borderRadius: theme.radius.pill, paddingVertical: theme.spacing.sm, paddingHorizontal: theme.spacing.md },
    pillActive: { backgroundColor: theme.colors.surface, borderColor: theme.colors.brandPrimary },
    pillText: { color: theme.colors.textSecondary, fontSize: 12, fontWeight: '600' },
    pillTextActive: { color: theme.colors.brandPrimary },
    iconBadge: {
      width: 28,
      height: 28,
      borderRadius: theme.radius.md,
      backgroundColor: theme.iconBubbles.primary.background,
      borderWidth: 1,
      borderColor: theme.iconBubbles.primary.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBadgeText: { color: theme.iconBubbles.primary.color, fontSize: 11, fontWeight: '800' },
    summaryCard: {
      backgroundColor: theme.colors.card,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderSoft,
      padding: theme.spacing.lg,
      gap: 10,
    },
    summaryCardLabel: { color: theme.colors.textSecondary, fontSize: 12, fontWeight: '600' },
    summaryCardAmount: { color: theme.colors.textPrimary, fontSize: 24, fontWeight: '800' },
    summaryCardStats: { flexDirection: 'row', gap: theme.spacing.sm },
  })
}

