export type ThemeMode = 'light' | 'dark'

export const kaswiseTokens = {
  light: {
    color: {
      bg: {
        base: '#F3F5FA',
        surface: '#FFFFFF',
        card: '#FFFFFF',
        muted: '#F8FAFD',
        elevated: '#FFFFFF',
        tabBar: '#FFFFFF',
        header: '#FFFFFF',
      },
      text: {
        primary: '#0C1A3A',
        secondary: '#4C5A78',
        muted: '#8A95AD',
        inverse: '#FFFFFF',
      },
      border: {
        soft: '#E2E7F2',
        strong: '#CBD5E3',
      },
      brand: {
        primary: '#4F46E5',
        accent: '#10B981',
      },
      status: {
        success: '#10B981',
        danger: '#EF4444',
        warning: '#F59E0B',
        info: '#38BDF8',
      },
      iconBubbles: {
        primary: { background: '#EEF2FF', color: '#4F46E5' },
        success: { background: '#ECFDF5', color: '#10B981' },
        warning: { background: '#FFFBEB', color: '#F59E0B' },
        danger: { background: '#FEF2F2', color: '#EF4444' },
        accent: { background: '#EFF6FF', color: '#38BDF8' },
        info: { background: '#F0F9FF', color: '#38BDF8' },
      },
    },
    radius: {
      sm: 10,
      md: 14,
      lg: 18,
      xl: 20,
      pill: 999,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      '2xl': 24,
      '3xl': 32,
    },
    typography: {
      fontFamily:
        'Inter, Poppins, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif',
      fontSize: {
        xs: 10,
        sm: 12,
        md: 14,
        lg: 16,
        xl: 18,
        '2xl': 20,
        '3xl': 24,
        '4xl': 28,
        '5xl': 32,
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      lineHeight: {
        tight: 1.2,
        normal: 1.4,
        relaxed: 1.6,
      },
      letterSpacing: {
        tight: -0.4,
        normal: 0,
        wide: 0.2,
      },
      support: { fontSize: 11, fontWeight: '700' },
      cardTitle: { fontSize: 16, fontWeight: '700' },
      sectionTitle: { fontSize: 15, fontWeight: '700' },
      metric: { fontSize: 20, fontWeight: '800' },
      screenTitle: { fontSize: 24, fontWeight: '800' },
      chip: { fontSize: 11, fontWeight: '800' },
    },
    opacity: {
      0: 0,
      10: 0.1,
      15: 0.15,
      18: 0.18,
      20: 0.2,
      25: 0.25,
      30: 0.3,
      40: 0.4,
      50: 0.5,
      60: 0.6,
      65: 0.65,
      70: 0.7,
      72: 0.72,
      75: 0.75,
      80: 0.8,
      90: 0.9,
      100: 1,
    },
    shadow: {
      sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 1,
      },
      md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 3,
      },
      lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
      },
      xl: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 12,
        elevation: 10,
      },
    },
  },
  dark: {
    color: {
      bg: {
        base: '#050C1B',
        surface: '#08132A',
        card: '#0A1730',
        muted: '#0E1E3D',
        elevated: '#162033',
        tabBar: '#0A1730',
        header: '#0A1730',
      },
      text: {
        primary: '#F8FAFF',
        secondary: '#B4C0DA',
        muted: '#7D8CA9',
        inverse: '#050C1B',
      },
      border: {
        soft: '#1A2A4C',
        strong: '#223861',
      },
      brand: {
        primary: '#4F46E5',
        accent: '#10B981',
      },
      status: {
        success: '#10B981',
        danger: '#EF4444',
        warning: '#F59E0B',
        info: '#38BDF8',
      },
      iconBubbles: {
        primary: { background: '#EEF2FF', color: '#4F46E5' },
        success: { background: '#ECFDF5', color: '#10B981' },
        warning: { background: '#FFFBEB', color: '#F59E0B' },
        danger: { background: '#FEF2F2', color: '#EF4444' },
        accent: { background: '#EFF6FF', color: '#38BDF8' },
        info: { background: '#F0F9FF', color: '#38BDF8' },
      },
    },
    radius: {
      sm: 10,
      md: 14,
      lg: 18,
      xl: 20,
      pill: 999,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 12,
      lg: 16,
      xl: 20,
      '2xl': 24,
      '3xl': 32,
    },
    typography: {
      fontFamily:
        'Inter, Poppins, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif',
      fontSize: {
        xs: 10,
        sm: 12,
        md: 14,
        lg: 16,
        xl: 18,
        '2xl': 20,
        '3xl': 24,
        '4xl': 28,
        '5xl': 32,
      },
      fontWeight: {
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      lineHeight: {
        tight: 1.2,
        normal: 1.4,
        relaxed: 1.6,
      },
      letterSpacing: {
        tight: -0.4,
        normal: 0,
        wide: 0.2,
      },
      support: { fontSize: 11, fontWeight: '700' },
      cardTitle: { fontSize: 16, fontWeight: '700' },
      sectionTitle: { fontSize: 15, fontWeight: '700' },
      metric: { fontSize: 20, fontWeight: '800' },
      screenTitle: { fontSize: 24, fontWeight: '800' },
      chip: { fontSize: 11, fontWeight: '800' },
    },
    opacity: {
      0: 0,
      10: 0.1,
      15: 0.15,
      18: 0.18,
      20: 0.2,
      25: 0.25,
      30: 0.3,
      40: 0.4,
      50: 0.5,
      60: 0.6,
      65: 0.65,
      70: 0.7,
      72: 0.72,
      75: 0.75,
      80: 0.8,
      90: 0.9,
      100: 1,
    },
    shadow: {
      sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
      },
      md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 3,
      },
      lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
      },
      xl: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 10,
      },
    },
  },
} as const
