-- Mobile/PWA stabilization: budget envelope defaults, sample-data cleanup, and sync safety.
-- Safe to re-run. The deletes target only deterministic sample seed rows generated by the app demo tool.

begin;

alter table if exists public.budget_envelopes
  alter column status set default 'active';

update public.budget_envelopes
set status = 'active'
where status is null;

-- Remove deterministic sample transactions created by Settings > Seed Sample Data.
delete from public.transaction_envelope_allocations tea
using public.transactions t
where tea.transaction_id = t.id
  and (
    t.catatan in (
      'Penerimaan gaji bulanan',
      'Pembayaran proyek freelance',
      'Bonus kinerja kuartalan'
    )
    or t.catatan like 'Pengeluaran % rutin'
  );

delete from public.transactions
where catatan in (
    'Penerimaan gaji bulanan',
    'Pembayaran proyek freelance',
    'Bonus kinerja kuartalan'
  )
  or catatan like 'Pengeluaran % rutin';

-- Remove deterministic sample budgets created by the same demo tool.
delete from public.budgets
where category in ('Makanan', 'Transportasi', 'Belanja', 'Tagihan', 'Hiburan')
  and period = 'monthly'
  and notify_at_percent = 80
  and is_active = true;

-- Recreate wallet sync trigger in case production drift dropped it.
drop trigger if exists sync_wallet_balance_from_transaction on public.transactions;
create trigger sync_wallet_balance_from_transaction
after insert or update or delete on public.transactions
for each row execute function public.sync_wallet_balance_from_transaction();

commit;
